#!/bin/sh
set -o errexit
echo -n 'version: '
read VERSION
echo -n ' minimum core version: '
read MINIMUM_CORE_VERSION
echo -n 'verified core version: '
read VERIFIED_CORE_VERSION
echo -n ' maximum core version: '
read MAXIMUM_CORE_VERSION
BASE_URL='https://gitlab.com/henry4k/foundryvtt-lang-de'
MASTER_FILES_URL="$BASE_URL/-/raw/master"
jq --slurp '.[0] * .[1]' module.json - > module-new.json <<EOF
{
    "version": "$VERSION",
    "compatibility": {
        "minimum": "$MINIMUM_CORE_VERSION",
        "verified": "$VERIFIED_CORE_VERSION",
        "maximum": "$MAXIMUM_CORE_VERSION"
    },
    "url": "$BASE_URL",
    "manifest": "$MASTER_FILES_URL/module.json",
    "download": "$BASE_URL/-/jobs/artifacts/v$VERSION/download?job=build",
    "bugs": "$BASE_URL/-/issues",
    "readme": "$MASTER_FILES_URL/README.md"
}
EOF
mv module-new.json module.json
git add module.json
#git add --all
git commit
git tag --force "v$VERSION"
git push --tags --force
git push
